swagger: "2.0"
info:
  version: 1.0.0
  title: "trentose2jan12-exam-aleametis"
  description: API of service to get and set information about astronauts
  termsOfService: http://swagger.io/terms/
  contact:
    name: Swagger API Team
    email: foo@example.com
    url: http://madskristensen.net
  license:
    name: MIT
    url: http://github.com/gruntjs/grunt/blob/master/LICENSE-MIT
host: trentose2jan12-aleametis.herokuapp.com
basePath: /api
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /astronauts:
    get:
      description: |
        Return all the astronauts and can filter the result by lastName
      operationId: findAstronauts
      parameters:
        - name: lastName
          in: query
          description: tag to filter by lastName
          required: false
          type: string
      responses:
        200:
          description: pet response
          schema:
            type: array
            items:
              $ref: '#/definitions/Astronaut'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
    post:
      description: Creates a new astronaut
      operationId: addAstronaut
      parameters:
        - name: astronaut
          in: body
          description: Astronaut to add to the collection
          required: true
          schema:
            $ref: '#/definitions/NewAstronaut'
      responses:
        200:
          description: astronaut response
          schema:
            $ref: '#/definitions/Astronaut'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
  /astronaut/{id}:
    get:
      description: Returns a single astronaut based on a ID
      operationId: find astronaut by id
      parameters:
        - name: id
          in: path
          description: ID of astronaut to fetch
          required: true
          type: string
      responses:
        200:
          description: astronaut response
          schema:
            $ref: '#/definitions/Astronaut'
        404:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
    put:
      description: modify a single astronaut based on the ID supplied
      operationId: modifyAstronaut
      parameters:
        - name: id
          in: path
          description: ID of astronaut to modify
          required: true
          type: string
        - name: astronaut
          in: body
          description: attributes to modify
          required: true
          schema:
            $ref: '#/definitions/NewAstronaut'
      responses:
        200:
          description: astronaut modified
          schema:
            $ref: '#/definitions/Astronaut'
        404:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  Astronaut:
    allOf:
      - $ref: '#/definitions/NewAstronaut'
      - required:
        - id
        properties:
          id:
            type: string
  NewAstronaut:
    required:
      - isInSpace
    properties:
      isInSpace:
        type: boolean
      firstName:
        type: string
      lastName:
        type: string
  Error:
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string